jobs:
  push-memory:
    runs-on: self-hosted
    needs: build-memory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag memory-site:latest ${{ secrets.DOCKER_USERNAME }}/memory:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/memory:latest

