name: Test Memory Workflow


on:
  push:
    branches:
      - develop


jobs:
  test-memory:
    
    runs-on: self-hosted

    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Test JPEG files
        run: |
          for jpg_file in $(find . -name "*.jpg"); do
            file "$jpg_file"
          done

